/* AUTO-GENERATED by scripts/generate-config.js — DO NOT EDIT MANUALLY */
/* Built: 2026-09-27T17:56:48.947Z */
/* To change: update sentinel/frontend/.env then run: npm run generate-config */
window.SENTINEL_BACKEND_URL = "https://spaceagent.nitishbiswas0099.workers.dev";
console.log('[SENTINEL] Backend URL:', window.SENTINEL_BACKEND_URL, '(loaded from config.js built at 2026-09-27T17:56:48.947Z)');
