"""
Phase 0 regression tests — data provenance labelling (backend).

These tests exist to stop the specific defect Phase 0 fixed: telemetry whose
numeric values were generated by ``random.uniform()`` was being served to the
UI labelled "Real ESA Telemetry".

Run:
    cd sentinel/backend && python3 -m unittest tests.test_phase0_provenance -v
"""

from __future__ import annotations

import json
import os
import sys
import unittest

_BACKEND_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _BACKEND_ROOT not in sys.path:
    sys.path.insert(0, _BACKEND_ROOT)

from app.api.provenance import (  # noqa: E402
    Provenance,
    default_note,
    describe,
    display_label,
    is_real,
    normalize,
    stamp,
)
from app.api.scenarios import get_all_scenarios, get_preset_scenarios  # noqa: E402

ESA_DUMP_DIR = os.path.join(_BACKEND_ROOT, "data", "esa_crash_dumps")

# The ONLY payload in this repository whose numeric telemetry was read from the
# ESA-ADB channel archives. Everything else is generated.
REAL_ESA_EVENT_IDS = {"id_109"}


class TestProvenanceVocabulary(unittest.TestCase):
    """The vocabulary itself must be closed and must fail safe."""

    def test_required_codes_exist(self):
        self.assertEqual(Provenance.REAL.value, "REAL")
        self.assertEqual(Provenance.SYNTHETIC.value, "SYNTHETIC")
        self.assertEqual(
            Provenance.SYNTHETIC_FROM_REAL_METADATA.value,
            "SYNTHETIC_FROM_REAL_METADATA",
        )

    def test_display_labels_use_required_wording(self):
        self.assertEqual(display_label(Provenance.REAL), "REAL ESA TELEMETRY")
        self.assertEqual(display_label(Provenance.SYNTHETIC), "SYNTHETIC DATA")
        self.assertEqual(
            display_label(Provenance.SYNTHETIC_FROM_REAL_METADATA),
            "SYNTHETIC FROM REAL METADATA",
        )

    def test_unknown_value_never_resolves_to_real(self):
        for bogus in ["real esa telemetry", "Real ESA Telemetry", "REALISH", "", None]:
            self.assertEqual(normalize(bogus), Provenance.UNKNOWN.value, msg=repr(bogus))
            self.assertFalse(is_real(normalize(bogus)), msg=repr(bogus))

    def test_is_real_is_true_only_for_real(self):
        self.assertTrue(is_real(Provenance.REAL))
        self.assertFalse(is_real(Provenance.SYNTHETIC))
        self.assertFalse(is_real(Provenance.SYNTHETIC_FROM_REAL_METADATA))
        self.assertFalse(is_real(Provenance.UNKNOWN))
        self.assertFalse(is_real(None))

    def test_synthetic_from_real_metadata_note_states_values_are_generated(self):
        note = default_note(Provenance.SYNTHETIC_FROM_REAL_METADATA).lower()
        self.assertIn("synthesized", note)
        self.assertIn("not measurements", note)

    def test_describe_derives_label_from_code_not_from_source_type(self):
        # A payload that lies in source_type must not keep that lie.
        payload = {
            "provenance": Provenance.SYNTHETIC_FROM_REAL_METADATA.value,
            "source_type": "Real ESA Telemetry",
        }
        resolved = describe(payload)
        self.assertEqual(resolved["source_type"], "SYNTHETIC FROM REAL METADATA")

    def test_stamp_sets_code_and_label_together(self):
        payload: dict = {}
        stamp(payload, Provenance.SYNTHETIC)
        self.assertEqual(payload["provenance"], "SYNTHETIC")
        self.assertEqual(payload["source_type"], "SYNTHETIC DATA")
        self.assertTrue(payload["source_note"])

    def test_stamp_preserves_an_existing_note(self):
        payload = {"source_note": "custom note"}
        stamp(payload, Provenance.SYNTHETIC)
        self.assertEqual(payload["source_note"], "custom note")


class TestScenarioProvenance(unittest.TestCase):
    """Every scenario served by /scenarios must be labelled correctly."""

    @classmethod
    def setUpClass(cls):
        cls.scenarios = get_all_scenarios()

    def test_scenarios_are_returned(self):
        self.assertGreater(len(self.scenarios), 0)

    def test_every_scenario_declares_a_provenance_code(self):
        for s in self.scenarios:
            with self.subTest(scenario_id=s.get("scenario_id")):
                self.assertIn("provenance", s)
                self.assertEqual(
                    s["provenance"],
                    normalize(s["provenance"]),
                    msg="provenance must be a recognised code",
                )

    def test_every_scenario_source_type_matches_its_code(self):
        for s in self.scenarios:
            with self.subTest(scenario_id=s.get("scenario_id")):
                self.assertEqual(s.get("source_type"), display_label(s["provenance"]))

    def test_no_scenario_uses_the_old_mislabel(self):
        for s in self.scenarios:
            with self.subTest(scenario_id=s.get("scenario_id")):
                self.assertNotEqual(s.get("source_type"), "Real ESA Telemetry")
                self.assertNotEqual(s.get("source_type"), "Synthetic Safe Mode")

    def test_only_scenario_4_is_labelled_real(self):
        real_ids = sorted(
            s["scenario_id"] for s in self.scenarios if is_real(s.get("provenance"))
        )
        self.assertEqual(
            real_ids,
            [4],
            msg="Only ESA-ADB id_109 (scenario 4) has real numeric telemetry",
        )

    def test_esa_derived_scenarios_are_synthetic_from_real_metadata(self):
        # Scenario ids 200-203 are produced by data_tools/generate_esa_scenarios.py,
        # which synthesizes the numeric values.
        generated = [s for s in self.scenarios if 200 <= int(s["scenario_id"]) <= 203]
        self.assertEqual(len(generated), 4, msg="expected 4 generated ESA scenarios")
        for s in generated:
            with self.subTest(scenario_id=s["scenario_id"]):
                self.assertEqual(
                    s["provenance"],
                    Provenance.SYNTHETIC_FROM_REAL_METADATA.value,
                )
                self.assertIn("SYNTHESIZED", s["source_note"])

    def test_synthetic_presets_are_labelled_synthetic(self):
        for s in get_preset_scenarios():
            if s["scenario_id"] == 4:
                continue
            with self.subTest(scenario_id=s["scenario_id"]):
                self.assertEqual(s["provenance"], Provenance.SYNTHETIC.value)

    def test_preset_notes_do_not_claim_real_telemetry(self):
        for s in self.scenarios:
            if is_real(s.get("provenance")):
                continue
            note = (s.get("source_note") or "").lower()
            with self.subTest(scenario_id=s.get("scenario_id")):
                self.assertNotIn(
                    "real anonymized telemetry",
                    note,
                    msg="non-real scenario must not describe itself as real telemetry",
                )


class TestEsaCrashDumpFilesOnDisk(unittest.TestCase):
    """The stored ESA payloads must declare provenance in the file itself."""

    def _dump_files(self):
        if not os.path.isdir(ESA_DUMP_DIR):
            self.skipTest(f"missing {ESA_DUMP_DIR}")
        return [
            os.path.join(ESA_DUMP_DIR, f)
            for f in sorted(os.listdir(ESA_DUMP_DIR))
            if f.endswith("_sentinel_only.json")
        ]

    def test_files_exist(self):
        self.assertGreater(len(self._dump_files()), 0)

    def test_every_file_is_valid_json_and_declares_provenance(self):
        for path in self._dump_files():
            with self.subTest(path=os.path.basename(path)):
                with open(path, "r", encoding="utf-8") as fh:
                    dump = json.load(fh)
                self.assertIn("provenance", dump)
                self.assertEqual(dump["provenance"], normalize(dump["provenance"]))

    def test_real_label_only_on_id_109(self):
        for path in self._dump_files():
            name = os.path.basename(path)
            with open(path, "r", encoding="utf-8") as fh:
                dump = json.load(fh)
            expect_real = any(eid in name for eid in REAL_ESA_EVENT_IDS)
            with self.subTest(file=name):
                self.assertEqual(
                    is_real(dump["provenance"]),
                    expect_real,
                    msg=f"{name}: REAL must be reserved for {sorted(REAL_ESA_EVENT_IDS)}",
                )


class TestGeneratorCannotEmitRealLabel(unittest.TestCase):
    """generate_esa_scenarios.py synthesizes values, so it must never say REAL."""

    def setUp(self):
        self.path = os.path.join(
            _BACKEND_ROOT, "data_tools", "generate_esa_scenarios.py"
        )
        if not os.path.isfile(self.path):
            self.skipTest("generate_esa_scenarios.py not found")
        with open(self.path, "r", encoding="utf-8") as fh:
            self.source = fh.read()

    def test_generator_stamps_synthetic_from_real_metadata(self):
        self.assertIn("SYNTHETIC_FROM_REAL_METADATA", self.source)

    def test_generator_does_not_write_the_real_label(self):
        self.assertNotIn('"source_type": "Real ESA Telemetry"', self.source)
        self.assertNotIn("Provenance.REAL", self.source)

    def test_generator_still_synthesizes_values(self):
        # Guards the premise of this whole test module: if the generator ever
        # starts reading real values, revisit its provenance code.
        self.assertIn("random.uniform", self.source)


if __name__ == "__main__":
    unittest.main(verbosity=2)
