/* AUTO-GENERATED by scripts/generate-config.js — DO NOT EDIT MANUALLY */
/* Built: 2026-08-09T16:57:27.203Z */
/* To change: update sentinel/frontend/.env then run: npm run generate-config */
window.SENTINEL_BACKEND_URL = "http://localhost:8000";
console.log('[SENTINEL] Backend URL:', window.SENTINEL_BACKEND_URL, '(loaded from config.js built at 2026-08-09T16:57:27.203Z)');
