"""
SENTINEL — Candidate Ranking (app/diagnosis/candidates.py)

Phase 6. Ranks the signature matches into hypotheses, deterministically.

Ranking inputs, all deterministic
---------------------------------
    signature_score       fraction of the fault's evidence weight that matched,
                          minus its contradictions
    propagation_score     whether this fault's subsystem can account for every
                          subsystem showing anomalies, using the declared
                          mechanisms in propagation.py
    specificity           how much DISCRIMINATING evidence matched, so a fault
                          separated by its own distinctive evidence outranks one
                          carried by generic symptoms
    onset_agreement       whether this fault's subsystem is the earliest to show
                          an anomaly, when the timestamps determine an order

No randomness, no model call, no sampling. The same report yields the same ranking.

What a score is not
-------------------
``score`` is a weighted sum of the four terms above, normalised to [0, 1]. It is
NOT a probability and NOT calibrated against outcomes — nothing in this repository
has measured how often a 0.8 hypothesis is correct. ``Hypothesis.score_basis``
carries that caveat into every record so it travels with the number.

Metrics for this stage are reported as top-1 candidate accuracy and top-3
candidate coverage, deliberately not as diagnosis accuracy: getting the right
fault into the candidate set is a different claim from producing a correct
diagnosis, which also requires the validation and recommendation stages.

The LLM's remaining role
------------------------
It receives this ranked set and may reorder it, explain it, or say the evidence is
insufficient. If it names a fault outside the set, ``classify_llm_fault()`` marks
the result UNSUPPORTED_HYPOTHESIS. Such a hypothesis is not discarded — a model
noticing something the rules missed is worth surfacing — but it is labelled, so it
can never be mistaken for a hypothesis the evidence produced.
"""

from __future__ import annotations

import hashlib
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field

from app.diagnosis.fault_dictionary import (
    FAULT_DICT_VERSION,
    FaultDefinition,
    SignatureRole,
    get_fault,
)
from app.diagnosis.propagation import (
    explained_subsystems,
    explain_path,
    onset_ordering,
)
from app.diagnosis.signature_match import (
    EvidenceIndex,
    SignatureMatch,
    build_evidence_index,
    match_faults,
)

HYPOTHESIS_ENGINE_VERSION = "1.0.0"
"""Version of the ranking logic. Bump when weights or terms change, since stored
hypotheses are only comparable within one version."""


#: Contribution of each term to the final score. Signature evidence dominates
#: because it is the most direct: it is what the detectors actually measured.
#: Propagation and onset are corroboration, and specificity is a tie-breaker
#: between faults with similar coverage.
SCORE_WEIGHTS: dict[str, float] = {
    "signature": 0.60,
    "propagation": 0.20,
    "specificity": 0.13,
    "onset": 0.07,
}

#: Candidates scoring below this are dropped from the ranked set. Set low on
#: purpose: the point of the stage is recall — getting the true fault into the
#: set — so a weak candidate is better retained and ranked last than excluded.
MIN_SCORE_TO_REPORT = 0.05

#: Cap on returned hypotheses. Enough for a differential without burying the
#: operator; the full match list is available separately.
MAX_HYPOTHESES = 8


class HypothesisOrigin(str, Enum):
    """Where a hypothesis came from. The central distinction of Phase 6."""

    DETERMINISTIC = "DETERMINISTIC"
    """Generated by signature matching against detector evidence."""

    LLM_RANKED = "LLM_RANKED"
    """Generated deterministically, then reordered or re-weighted by the LLM.
    Still grounded in matched evidence."""

    UNSUPPORTED_HYPOTHESIS = "UNSUPPORTED_HYPOTHESIS"
    """Named by the LLM but NOT in the deterministic candidate set.

    Retained rather than dropped, because a model may notice a pattern the rules
    do not encode. But it carries no matched evidence, so it must never be
    presented alongside evidence-backed hypotheses without this label. This is
    the mechanism that stops the model inventing a fault and having it treated as
    a finding.
    """


class EvidenceItem(BaseModel):
    """One piece of evidence for or against a hypothesis."""

    model_config = ConfigDict(frozen=True)

    channel: str
    condition: str
    role: str
    state: str
    rationale: str
    detectors: list[str] = Field(default_factory=list)
    severity: Optional[str] = None
    timestamp: Optional[str] = None
    anomaly_ids: list[str] = Field(default_factory=list)
    weight: float = 0.0

    source: str = Field(
        default="TELEMETRY",
        description=(
            "TELEMETRY for a channel predicate, CONTEXT for a predicate over a "
            "recorded context fact such as an array relay position."
        ),
    )
    observed_from: Optional[str] = Field(
        default=None,
        description=(
            "For CONTEXT evidence, the dump field that decided it and the value "
            "it held. None for telemetry, where channel and detectors carry the "
            "provenance."
        ),
    )


class Hypothesis(BaseModel):
    """A ranked fault hypothesis, with every field the Phase 6 spec requires."""

    model_config = ConfigDict(frozen=True)

    hypothesis_id: str = Field(
        ..., description="Stable content-derived id, reproducible across runs",
    )
    fault_id: str
    fault_name: str
    subsystem: str
    rank: int = Field(..., ge=1)
    score: float = Field(..., ge=0.0, le=1.0)

    supporting_evidence: list[EvidenceItem] = Field(default_factory=list)
    contradicting_evidence: list[EvidenceItem] = Field(default_factory=list)
    undetermined_evidence: list[EvidenceItem] = Field(
        default_factory=list,
        description=(
            "Signatures that could not be evaluated because the channel had no "
            "reading. Reported so a reader can tell weak evidence from absent "
            "telemetry."
        ),
    )

    affected_channels: list[str] = Field(default_factory=list)
    timestamps: list[str] = Field(default_factory=list)
    earliest_onset_seconds: Optional[float] = None

    detector_evidence: list[str] = Field(
        default_factory=list,
        description="Anomaly ids from the AnomalyReport backing this hypothesis",
    )

    origin: HypothesisOrigin = HypothesisOrigin.DETERMINISTIC
    severity: str = ""
    possible_causes: list[str] = Field(default_factory=list)
    recovery_procedure_ids: list[str] = Field(default_factory=list)
    causal_chain: list[str] = Field(default_factory=list)

    score_components: dict[str, float] = Field(default_factory=dict)
    score_basis: str = Field(
        default=(
            "Deterministic weighted sum of matched signature evidence, "
            "subsystem propagation plausibility, evidence specificity and onset "
            "ordering. NOT a probability and NOT calibrated against outcomes."
        ),
    )
    propagation_notes: list[str] = Field(default_factory=list)
    unexplained_subsystems: list[str] = Field(
        default_factory=list,
        description=(
            "Subsystems showing anomalies that a fault here cannot account for. "
            "A non-empty list weakens the hypothesis as a single root cause."
        ),
    )
    is_evidence_backed: bool = Field(
        default=True,
        description="False for an UNSUPPORTED_HYPOTHESIS.",
    )
    notes: Optional[str] = None


class HypothesisSet(BaseModel):
    """The complete output of the deterministic engine."""

    model_config = ConfigDict(frozen=True)

    engine_version: str = HYPOTHESIS_ENGINE_VERSION
    fault_dict_version: str = FAULT_DICT_VERSION
    generated_by: str = Field(
        default="deterministic_signature_matching",
        description="Never an LLM. Asserted by test.",
    )
    uses_llm: bool = False

    hypotheses: list[Hypothesis] = Field(default_factory=list)
    considered_fault_ids: list[str] = Field(
        default_factory=list,
        description="Every fault evaluated, including those rejected",
    )
    rejected: dict[str, str] = Field(
        default_factory=dict,
        description="fault_id -> why it was not a candidate",
    )

    anomalous_subsystems: list[str] = Field(default_factory=list)
    unknown_channels: list[str] = Field(
        default_factory=list,
        description=(
            "Anomalous channels with no subsystem attribution, typically "
            "anonymized ESA-ADB channels. They cannot support any fault."
        ),
    )
    onset_analysis: dict[str, Any] = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)
    summary: str = ""

    @property
    def top(self) -> Optional[Hypothesis]:
        return self.hypotheses[0] if self.hypotheses else None

    def top_n_fault_ids(self, n: int) -> list[str]:
        return [h.fault_id for h in self.hypotheses[:n]]

    def candidate_fault_ids(self) -> set[str]:
        """The set an LLM may choose from without being marked unsupported."""
        return {h.fault_id for h in self.hypotheses}


# ═══════════════════════════════════════════════════════════════════════════
# SCORING
# ═══════════════════════════════════════════════════════════════════════════

def _propagation_score(
    definition: FaultDefinition,
    index: EvidenceIndex,
) -> tuple[float, list[str], list[str]]:
    """How well a fault here accounts for every subsystem showing anomalies.

    A fault explaining all of them is a better single root cause than one leaving
    some unaccounted for. When only its own subsystem is anomalous the question
    does not arise and the term is neutral rather than favourable — a single
    subsystem anomaly is not evidence of propagation.
    """
    observed = [s for s in index.anomalous_subsystems if s != "UNKNOWN"]
    if not observed:
        return 0.5, ["No subsystem-attributed anomalies to explain."], []

    if definition.subsystem == "MULTI":
        # A cascade is the better explanation exactly when several subsystems are
        # involved, and a poor one when only one is.
        if len(observed) >= 2:
            return 1.0, [
                f"{len(observed)} subsystems show anomalies "
                f"({', '.join(observed)}), which is what a cascade means."
            ], []
        return 0.1, [
            "Only one subsystem shows anomalies, so a cross-subsystem cascade "
            "is not supported."
        ], []

    explained, unexplained = explained_subsystems(definition.subsystem, observed)

    # Weight each subsystem by the strength of the evidence implicating it rather
    # than counting subsystems equally. Measured reason: on a simulated comms
    # fault, the simulator's injected 5% NaN dropout put one V_bat reading into
    # the anomaly list, which made EPS a subsystem every comms hypothesis had to
    # explain. Counting equally, that single dropout carried the same weight as
    # two hard-limit violations on the comms channels, so telemetry-path noise
    # moved the ranking. See _SUBSYSTEM_EVIDENCE_WEIGHT in signature_match.py.
    strength = index.subsystem_evidence_strength or {}

    def weight_of(subsystem: str) -> float:
        return float(strength.get(subsystem, 1.0))

    notes: list[str] = []
    for subsystem in explained:
        mechanism = explain_path(definition.subsystem, subsystem)
        if mechanism:
            notes.append(f"{definition.subsystem} -> {subsystem}: {mechanism}")
    for subsystem in unexplained:
        notes.append(
            f"{definition.subsystem} -> {subsystem}: no declared propagation "
            f"path, so this fault does not account for the {subsystem} anomaly "
            f"(evidence weight {weight_of(subsystem):.2f})."
        )

    explained_weight = sum(weight_of(s) for s in explained)
    total_weight = sum(weight_of(s) for s in observed)
    if total_weight <= 0.0:
        return 0.5, notes, list(unexplained)

    score = explained_weight / total_weight
    return round(score, 4), notes, list(unexplained)


def _specificity_score(match: SignatureMatch,
                       definition: FaultDefinition) -> float:
    """Fraction of the fault's DISCRIMINATING evidence that matched.

    This is what stops a fault with many generic signatures outranking one whose
    distinctive evidence is present. A fault with no discriminating signatures —
    only MULTI_CASCADE — scores neutral rather than zero, since it is not being
    penalised for a property it declares it does not have.
    """
    discriminating = definition.discriminating_signatures
    if not discriminating:
        return 0.5

    matched_keys = {m.signature_key for m in match.matched}
    hits = sum(1 for s in discriminating if s.key in matched_keys)
    return round(hits / len(discriminating), 4)


def _onset_score(definition: FaultDefinition, ordering: dict[str, Any]) -> float:
    """Whether this fault's subsystem is the earliest to show an anomaly.

    Neutral when the ordering is undetermined. Rewarding a guess would let a
    coin-flip on tied timestamps decide the ranking.
    """
    if not ordering.get("determined"):
        return 0.5
    earliest = ordering.get("earliest")
    if earliest is None:
        return 0.5
    if definition.subsystem == "MULTI":
        return 0.5
    from app.ingest.channel_dict import resolve_subsystem

    if resolve_subsystem(definition.subsystem) is resolve_subsystem(earliest):
        return 1.0
    return 0.25


def _hypothesis_id(fault_id: str, match: SignatureMatch) -> str:
    """Stable id derived from the fault and the evidence that produced it.

    Content-derived rather than sequential, so the same evidence yields the same
    id on a re-run and two runs can be compared.
    """
    material = "|".join([
        fault_id,
        f"{match.signature_score:.4f}",
        ",".join(f"{m.channel}:{m.condition}" for m in match.matched),
        ",".join(f"{m.channel}:{m.condition}" for m in match.contradicted),
    ])
    digest = hashlib.sha256(material.encode("utf-8")).hexdigest()[:12]
    return f"HYP-{digest}"


def _to_items(records: tuple, ) -> list[EvidenceItem]:
    return [
        EvidenceItem(
            channel=r.channel, condition=r.condition, role=r.role,
            state=r.state, rationale=r.rationale, detectors=list(r.detectors),
            severity=r.severity, timestamp=r.timestamp,
            anomaly_ids=list(r.anomaly_ids), weight=r.weight,
            source=getattr(r, "source", "TELEMETRY"),
            observed_from=getattr(r, "observed_from", None),
        )
        for r in records
    ]


# ═══════════════════════════════════════════════════════════════════════════
# GENERATION
# ═══════════════════════════════════════════════════════════════════════════

def generate_hypotheses(
    report: Any,
    crash_dump: Optional[dict[str, Any]] = None,
    max_hypotheses: int = MAX_HYPOTHESES,
    min_score: float = MIN_SCORE_TO_REPORT,
) -> HypothesisSet:
    """Produce a ranked hypothesis set from detector evidence alone.

    Args:
        report: An ``AnomalyReport`` from the Phase 2 detection pipeline.
        crash_dump: The dump, used to learn which channels were examined. Without
            it a channel with no anomaly cannot be told from a channel with no
            reading, which weakens the NOMINAL and contradiction predicates.
        max_hypotheses: Cap on the returned list.
        min_score: Candidates below this are recorded as rejected.

    Returns:
        A ``HypothesisSet``. Deterministic: the same inputs give byte-identical
        output.
    """
    index, matches = match_faults(report, crash_dump)
    ordering = onset_ordering(index.subsystem_onsets)

    scored: list[tuple[float, str, Hypothesis]] = []
    rejected: dict[str, str] = {}

    for match in matches:
        definition = get_fault(match.fault_id)
        if definition is None:  # pragma: no cover — ids come from the dictionary
            continue

        if not match.eligible:
            rejected[match.fault_id] = match.ineligible_reason or "ineligible"
            continue

        propagation, notes, unexplained = _propagation_score(definition, index)
        specificity = _specificity_score(match, definition)
        onset = _onset_score(definition, ordering)

        components = {
            "signature": match.signature_score,
            "propagation": propagation,
            "specificity": specificity,
            "onset": onset,
        }
        score = round(
            sum(SCORE_WEIGHTS[k] * v for k, v in components.items()), 4,
        )

        # A fault with no matched evidence at all is not a candidate, whatever
        # its corroboration terms say. Propagation plausibility alone is not
        # evidence that a fault occurred.
        if not match.matched:
            rejected[match.fault_id] = (
                "no signature matched the detector evidence"
            )
            continue

        if score < min_score:
            rejected[match.fault_id] = (
                f"score {score:.3f} below the reporting threshold {min_score}"
            )
            continue

        detector_ids: list[str] = []
        for record in match.matched:
            detector_ids.extend(record.anomaly_ids)

        scored.append((score, definition.fault_id, Hypothesis(
            hypothesis_id=_hypothesis_id(definition.fault_id, match),
            fault_id=definition.fault_id,
            fault_name=definition.fault_name,
            subsystem=definition.subsystem,
            rank=1,  # assigned after sorting
            score=score,
            supporting_evidence=_to_items(match.matched),
            contradicting_evidence=_to_items(match.contradicted),
            undetermined_evidence=_to_items(match.undetermined),
            affected_channels=list(match.affected_channels),
            timestamps=list(match.timestamps),
            earliest_onset_seconds=match.earliest_onset,
            detector_evidence=sorted(set(detector_ids)),
            origin=HypothesisOrigin.DETERMINISTIC,
            severity=definition.severity.value,
            possible_causes=list(definition.possible_causes),
            recovery_procedure_ids=list(definition.recovery_procedure_ids),
            causal_chain=list(definition.causal_chain),
            score_components=components,
            propagation_notes=notes,
            unexplained_subsystems=unexplained,
            is_evidence_backed=True,
            notes=definition.notes,
        )))

    # Descending score, then fault_id — a deterministic tie-break that does not
    # depend on dictionary order.
    scored.sort(key=lambda item: (-item[0], item[1]))

    hypotheses = [
        h.model_copy(update={"rank": position})
        for position, (_score, _fid, h) in enumerate(scored[:max_hypotheses],
                                                     start=1)
    ]
    for _score, fault_id, _h in scored[max_hypotheses:]:
        rejected[fault_id] = f"ranked below the top {max_hypotheses}"

    warnings: list[str] = []
    if not hypotheses:
        warnings.append(
            "No fault signature matched the detector evidence. This is not a "
            "clean bill of health: it means the evidence does not correspond to "
            "any fault in the dictionary."
        )
    if index.unknown_channels:
        warnings.append(
            f"{len(index.unknown_channels)} anomalous channel(s) have no "
            f"subsystem attribution and cannot support any fault: "
            f"{', '.join(index.unknown_channels[:6])}"
            + ("..." if len(index.unknown_channels) > 6 else "")
        )
    if not ordering.get("determined"):
        warnings.append(
            f"Onset ordering undetermined ({ordering.get('reason')}), so root "
            f"cause was not inferred from timing."
        )
    if len(hypotheses) == 1:
        warnings.append(
            "Only one hypothesis is evidence-backed. A single candidate is not "
            "a confirmed diagnosis; it means the dictionary offers no competing "
            "explanation for this evidence."
        )

    if hypotheses:
        top = hypotheses[0]
        summary = (
            f"{len(hypotheses)} deterministic hypothesis(es) from "
            f"{index.total_anomalies} anomaly(ies); top candidate "
            f"{top.fault_id} at {top.score:.2f} "
            f"({len(top.supporting_evidence)} supporting, "
            f"{len(top.contradicting_evidence)} contradicting)"
        )
    else:
        summary = (
            f"No hypothesis matched {index.total_anomalies} anomaly(ies) across "
            f"{len(index.channels)} channel(s)."
        )

    return HypothesisSet(
        hypotheses=hypotheses,
        considered_fault_ids=[m.fault_id for m in matches],
        rejected=rejected,
        anomalous_subsystems=list(index.anomalous_subsystems),
        unknown_channels=list(index.unknown_channels),
        onset_analysis=ordering,
        warnings=warnings,
        summary=summary,
    )


# ═══════════════════════════════════════════════════════════════════════════
# LLM BOUNDARY
# ═══════════════════════════════════════════════════════════════════════════

def classify_llm_fault(
    fault_id: object,
    candidate_set: HypothesisSet,
) -> tuple[HypothesisOrigin, Optional[str]]:
    """Classify a fault name the LLM produced.

    Returns ``(origin, note)``:

        LLM_RANKED               the fault is in the deterministic candidate set
        UNSUPPORTED_HYPOTHESIS   it is not

    An unsupported hypothesis is not an error and is not discarded. It is
    labelled, because the alternative — accepting it silently — is what let a
    single model call be both the source and the judge of the diagnosis.

    A fault in the dictionary but rejected by the matcher is still unsupported:
    the matcher rejected it against the evidence, and the model naming it anyway
    does not restore the evidence.
    """
    name = "" if fault_id is None else str(fault_id).strip().upper()
    if not name:
        return HypothesisOrigin.UNSUPPORTED_HYPOTHESIS, (
            "No fault_id supplied, so the hypothesis cannot be matched to any "
            "candidate."
        )

    if name in candidate_set.candidate_fault_ids():
        return HypothesisOrigin.LLM_RANKED, None

    rejection = candidate_set.rejected.get(name)
    if rejection is not None:
        return HypothesisOrigin.UNSUPPORTED_HYPOTHESIS, (
            f"{name} is a known fault but the deterministic engine rejected it "
            f"for this evidence: {rejection}"
        )

    if get_fault(name) is not None:
        return HypothesisOrigin.UNSUPPORTED_HYPOTHESIS, (
            f"{name} is in the fault dictionary but was not generated as a "
            f"candidate from this evidence."
        )

    return HypothesisOrigin.UNSUPPORTED_HYPOTHESIS, (
        f"{name} is not in the SENTINEL fault dictionary. It was produced by "
        f"the language model and has no matched detector evidence."
    )


def engine_status() -> dict:
    """Describe the engine, for the API and tests."""
    from app.diagnosis.fault_dictionary import dictionary_status
    from app.diagnosis.propagation import propagation_status
    from app.diagnosis.signature_match import matching_status

    return {
        "engine_version": HYPOTHESIS_ENGINE_VERSION,
        "uses_llm": False,
        "score_weights": dict(SCORE_WEIGHTS),
        "min_score_to_report": MIN_SCORE_TO_REPORT,
        "max_hypotheses": MAX_HYPOTHESES,
        "score_is_probability": False,
        "score_is_calibrated": False,
        "metric_names": ["top1_candidate_accuracy", "top3_candidate_coverage"],
        "metric_caveat": (
            "These measure whether the deterministic stage puts the labelled "
            "fault into its candidate set. They are NOT diagnosis accuracy, "
            "which would also require the validation and recommendation stages."
        ),
        "origins": [o.value for o in HypothesisOrigin],
        "fault_dictionary": dictionary_status(),
        "propagation": propagation_status(),
        "matching": matching_status(),
    }
