#!/usr/bin/env node
/**
 * generate-config.js
 *
 * Reads REACT_APP_BACKEND_URL from the .env file (or process.env) and
 * writes public/config.js — a runtime config loaded by static HTML pages.
 *
 * Usage:
 *   node scripts/generate-config.js
 *
 * On Render / Fly.io / Railway: set REACT_APP_BACKEND_URL as an environment
 * variable in the platform dashboard. Run this script in the build step:
 *   node scripts/generate-config.js && npx serve . -l $PORT
 */

const fs = require('fs');
const path = require('path');

// ─── SINGLE SOURCE OF TRUTH FOR THE BACKEND URL ───────────────────
// REACT_APP_BACKEND_URL in sentinel/frontend/.env is the only value an
// operator should need to set. This script writes it into config.js, which
// both frontends read at runtime via window.SENTINEL_BACKEND_URL.
//
// DEFAULT_BACKEND_URL below is the fallback when no .env is present. If you
// change it, change the matching fallback in all of these, or the ports will
// drift apart again (they previously read 8000 / 8001 / 8005):
//   - sentinel/frontend/index.html          (SENTINEL_DEFAULT_BACKEND_URL)
//   - sentinel/frontend/public/landing.html (SENTINEL_DEFAULT_BACKEND_URL)
//   - sentinel/frontend/src/App.jsx         (DEFAULT_BACKEND_URL)
//   - sentinel/frontend/.env.example
const DEFAULT_BACKEND_URL = 'https://spaceagent.nitishbiswas0099.workers.dev';

// Load .env if present (manual simple parser — no dotenv dependency needed)
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

const backendUrl = process.env.REACT_APP_BACKEND_URL || DEFAULT_BACKEND_URL;

const timestamp = new Date().toISOString();

const configContent = `/* AUTO-GENERATED by scripts/generate-config.js — DO NOT EDIT MANUALLY */
/* Built: ${timestamp} */
/* To change: update sentinel/frontend/.env then run: npm run generate-config */
window.SENTINEL_BACKEND_URL = "${backendUrl}";
console.log('[SENTINEL] Backend URL:', window.SENTINEL_BACKEND_URL, '(loaded from config.js built at ${timestamp})');
`;

const targets = [
  path.join(__dirname, '..', 'config.js'),
  path.join(__dirname, '..', 'public', 'config.js'),
  path.join(__dirname, '..', 'dashboard', 'config.js'),
  path.join(__dirname, '..', 'build', 'config.js'),
  path.join(__dirname, '..', '..', 'backend', 'dashboard', 'config.js'),
];

for (const target of targets) {
  try {
    const parentDir = path.dirname(target);
    if (!fs.existsSync(parentDir)) fs.mkdirSync(parentDir, { recursive: true });
    fs.writeFileSync(target, configContent, 'utf8');
  } catch (e) {}
}

console.log(`✅ Generated config.js with SENTINEL_BACKEND_URL="${backendUrl}" across all directories`);

// Sync static assets so serve can resolve /vendor and /static at root and /dashboard
function copyRecursiveSync(src, dest) {
  const exists = fs.existsSync(src);
  const stats = exists && fs.statSync(src);
  const isDirectory = exists && stats.isDirectory();
  if (isDirectory) {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    fs.readdirSync(src).forEach((childItemName) => {
      copyRecursiveSync(path.join(src, childItemName), path.join(dest, childItemName));
    });
  } else if (exists) {
    const destDir = path.dirname(dest);
    if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

try {
  const rootDir = path.join(__dirname, '..');
  const publicVendor = path.join(rootDir, 'public', 'vendor');
  const rootVendor = path.join(rootDir, 'vendor');
  if (fs.existsSync(publicVendor)) copyRecursiveSync(publicVendor, rootVendor);

  const buildStatic = path.join(rootDir, 'build', 'static');
  const rootStatic = path.join(rootDir, 'static');
  const dashboardStatic = path.join(rootDir, 'dashboard', 'static');
  if (fs.existsSync(buildStatic)) {
    copyRecursiveSync(buildStatic, rootStatic);
    copyRecursiveSync(buildStatic, dashboardStatic);
  }

  const buildIndex = path.join(rootDir, 'build', 'index.html');
  const dashboardIndex = path.join(rootDir, 'dashboard', 'index.html');
  if (fs.existsSync(buildIndex)) {
    copyRecursiveSync(buildIndex, dashboardIndex);
  }

  const landingSrc = path.join(rootDir, 'public', 'landing.html');
  if (fs.existsSync(landingSrc)) {
    const landingTargets = [
      path.join(rootDir, 'public', 'landing', 'index.html'),
      path.join(rootDir, 'public', 'public', 'landing.html'),
      path.join(rootDir, 'public', 'public', 'landing', 'index.html'),
      path.join(rootDir, 'build', 'landing', 'index.html'),
      path.join(rootDir, 'build', 'landing.html'),
      path.join(rootDir, 'build', 'public', 'landing.html'),
      path.join(rootDir, 'build', 'public', 'landing', 'index.html'),
      path.join(rootDir, 'dashboard', 'landing', 'index.html'),
      path.join(rootDir, 'dashboard', 'landing.html'),
      path.join(rootDir, 'dashboard', 'public', 'landing.html'),
    ];
    for (const lt of landingTargets) {
      copyRecursiveSync(landingSrc, lt);
    }
  }
} catch (e) {
  console.warn('⚠️ Asset sync warning:', e.message);
}
