"""
SENTINEL — Preset Crash Dump Scenarios (scenarios.py)

Provides the demo UI with ready-made crash dump payloads that match the
CrashDumpRequest schema defined in models.py.

Each scenario is a complete dict that FastAPI can validate against
CrashDumpRequest.  The frontend fetches these via GET /scenarios and
renders them in the scenario selector dropdown.

Provenance (see app/api/provenance.py for the authoritative vocabulary):
  - ``SYNTHETIC``                     : generated by fault_simulator.py
  - ``SYNTHETIC_FROM_REAL_METADATA``  : real ESA-ADB labels, generated numbers
  - ``REAL``                          : numeric telemetry read from ESA-ADB itself

Only scenario 4 (ESA-ADB Mission1 id_109) is REAL. It was built by
data_tools/esa_adb_crash_dump.py, which reads the actual channel pickles.

Sampling policy (Phase 15)
--------------------------
The physics layer (app/estimation) needs each modelled channel reported
FRESHLY at two or more timed samples to step a prediction, and the baseline
audit (BASELINE_REPORT.md, F-01) found the synthetic presets sampled every
modelled channel exactly once. Scenarios 1, 2, 3, 5 and 6 were therefore
resampled: pre-fault NOMINAL samples and the fault-evolution samples the
original story already implied were added to the canonical window with their
timestamps, and the legacy snapshot rows were kept in sync.

The additions are NOT fabricated random values: each one is the same physical
quantity the scenario already narrated (the healthy array current before the
undervolt, the wheel speed the gyro upset transfers momentum to, the
component temperature the thermal runaway drives through the OBC limit).
The physics contract (app/estimation/window_adequacy.py) decides whether the
resulting window is steppable, and reports UNDER_SAMPLED_FOR_PHYSICS
explicitly when it is not.

Legacy rows carry no timestamps; the adapter (app/api/adapters.py) anchors
them at T-0s. A legacy value must therefore agree with the T-0s window sample
of the same channel, or the merged window self-contradicts.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any

from app.api.provenance import Provenance, describe, stamp

logger = logging.getLogger(__name__)


def _fill_bounds_from_dictionary(scenario: dict[str, Any]) -> dict[str, Any]:
    """Fill each legacy telemetry row's bounds from the channel dictionary.

    Phase 5. The preset scenarios repeated ``nominal_min`` / ``nominal_max`` on
    every reading — 27 literal pairs across the six presets, all of them copies of
    the detector's table. They happened to agree with it, but nothing checked
    that, and a scenario carrying a stale bound would have made the detector
    report a violation the operator could not explain from the catalogue.

    Bounds now come from ``app.ingest.channel_dict.hard_limits()``, the same
    source the detector compares against, so a scenario cannot disagree with the
    detector about where a limit is.

    A row for a channel the dictionary does not know keeps whatever bounds it
    carries, and gains none. Nothing is invented for an unknown channel.
    """
    from app.ingest.channel_dict import get_channel

    rows = scenario.get("pre_fault_telemetry")
    if not isinstance(rows, list):
        return scenario

    for row in rows:
        if not isinstance(row, dict):
            continue
        definition = get_channel(row.get("parameter"))
        if definition is None:
            continue
        low, high = definition.hard_limits
        if low is not None:
            row["nominal_min"] = low
        if high is not None:
            row["nominal_max"] = high
        if definition.unit and not row.get("unit"):
            row["unit"] = definition.unit
    return scenario


def get_preset_scenarios() -> list[dict[str, Any]]:
    """Return the built-in demo scenarios.

    Each entry mirrors the CrashDumpRequest schema.  Legacy fields
    (pre_fault_telemetry, event_log, hardware_state, operating_context)
    are preserved so the existing frontend renders them correctly.

    Fields added for provenance transparency:
      - ``provenance``: Machine-readable code from app.api.provenance.Provenance.
      - ``source_type``: Human-readable label DERIVED from ``provenance``.
      - ``source_note``: One-sentence provenance disclaimer.

    ``source_type`` is derived rather than hand-written so it cannot drift
    away from the actual provenance of the numbers.
    """
    return [
        # ── Scenario 1: ADCS Gyroscope SEU ────────────────────────────────
        {
            "scenario_id": 1,
            "fault_type": "ADCS_GYRO_SEU",
            "provenance": Provenance.SYNTHETIC.value,
            "source_note": "Simulated crash dump modelled on ECSS-E-ST-70-11C SEU fault signatures. Not spacecraft data.",
            "incident_id": "INC-2026-0001",
            "fault_register": "0x00000080",
            "safe_mode_trigger": "ADCS_ERROR",
            "telecommand_context": {
                "event_id": 1,
                "telecommand": "telecommand_12",
                "execution_timestamp": "2026-06-12T03:47:23Z",
                "gap_seconds": 62.0,
                "gap_classification": "burst",
                "gap_percentile": 8.4,
                "anomaly_flag": True,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-120s", "parameter": "Gyro_rate_degs",
                 "value": 0.5, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "SEU_counter",
                 "value": 0.0, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "RW_speed_rpm",
                 "value": 4500.0, "status": "NOMINAL"},
                {"timestamp": "T-60s", "parameter": "Gyro_rate_degs",
                 "value": 0.52, "status": "NOMINAL"},
                {"timestamp": "T-60s", "parameter": "SEU_counter",
                 "value": 3.0, "status": "ANOMALOUS"},
                {"timestamp": "T-60s", "parameter": "RW_speed_rpm",
                 "value": 4502.0, "status": "NOMINAL"},
                {"timestamp": "T-30s", "parameter": "Gyro_rate_degs",
                 "value": 4.5, "status": "CRITICAL"},
                {"timestamp": "T-30s", "parameter": "Attitude_error_deg",
                 "value": 7.3, "status": "CRITICAL"},
                {"timestamp": "T-30s", "parameter": "RW_speed_rpm",
                 "value": 4498.0, "status": "NOMINAL"},
                {"timestamp": "T-10s", "parameter": "V_bat",
                 "value": 30.2, "status": "NOMINAL"},
                {"timestamp": "T-0s", "parameter": "Gyro_rate_degs",
                 "value": "NaN", "status": "CRITICAL"},
                {"timestamp": "T-0s", "parameter": "Attitude_error_deg",
                 "value": 7.4, "status": "CRITICAL"},
                {"timestamp": "T-0s", "parameter": "SEU_counter",
                 "value": 3.0, "status": "ANOMALOUS"},
            ],
            # --- Legacy fields consumed by the existing frontend ---
            # Kept in sync with the window: legacy rows carry no timestamps and
            # the adapter anchors them at T-0s, so a legacy value that disagreed
            # with the T-0s window sample would be a self-contradictory reading.
            "pre_fault_telemetry": [
                {"parameter": "Gyro_rate_degs", "value": "NaN"},
                {"parameter": "Attitude_error_deg", "value": 7.4},
                {"parameter": "SEU_counter", "value": 3.0},
                {"parameter": "RW_speed_rpm", "value": 4500.0},
                {"parameter": "OBC_temp_C", "value": 24.5},
            ],
            "event_log": [
                {"timestamp": "T-62s", "source": "OBC_KERNEL",
                 "message": "SEU counter incremented: 3"},
                {"timestamp": "T-30s", "source": "ADCS_ATTITUDE",
                 "message": "Attitude error exceeded threshold (7.3 deg)"},
                {"timestamp": "T-0s", "source": "ADCS_MANAGER",
                 "message": "GYRO_A health status: NaN"},
                {"timestamp": "T-0s", "source": "FDIR_CORE",
                 "message": "Safe Mode entry triggered by ADCS_ERROR"},
            ],
            "hardware_state": {
                "active_gyro": "A",
                "seu_flags": "0x03",
                "watchdog_status": "nominal",
            },
            "operating_context": {
                "eclipse_fraction": 0.0,
                "sun_sensor_angle_deg": 12.5,
                "time_since_contact_s": 1200,
            },
        },
        # ── Scenario 2: EPS Power Fault ───────────────────────────────────
        {
            "scenario_id": 2,
            "fault_type": "EPS_SOLAR_UNDERVOLT",
            "provenance": Provenance.SYNTHETIC.value,
            "source_note": "Simulated crash dump modelled on solar array undervoltage behaviour. Not spacecraft data.",
            "incident_id": "INC-2026-0002",
            "fault_register": "0x00000002",
            "safe_mode_trigger": "EPS_UNDER_VOLT",
            "telecommand_context": {
                "event_id": 2,
                "telecommand": "telecommand_45",
                "execution_timestamp": "2026-06-12T04:10:00Z",
                "gap_seconds": 300.0,
                "gap_classification": "stale",
                "gap_percentile": 92.1,
                "anomaly_flag": True,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-300s", "parameter": "I_sa",
                 "value": 8.4, "status": "NOMINAL"},
                {"timestamp": "T-300s", "parameter": "SoC_pct",
                 "value": 85.0, "status": "NOMINAL"},
                {"timestamp": "T-300s", "parameter": "V_bat",
                 "value": 30.2, "status": "NOMINAL"},
                {"timestamp": "T-300s", "parameter": "V_bus",
                 "value": 30.0, "status": "NOMINAL"},
                {"timestamp": "T-300s", "parameter": "Heater_power_W",
                 "value": 15.0, "status": "NOMINAL"},
                {"timestamp": "T-180s", "parameter": "I_sa",
                 "value": 0.0, "status": "CRITICAL"},
                {"timestamp": "T-180s", "parameter": "V_bat",
                 "value": 21.8, "status": "CRITICAL"},
                {"timestamp": "T-180s", "parameter": "SoC_pct",
                 "value": 14.2, "status": "CRITICAL"},
                {"timestamp": "T-180s", "parameter": "V_bus",
                 "value": 24.1, "status": "ANOMALOUS"},
                {"timestamp": "T-120s", "parameter": "V_bus",
                 "value": 24.1, "status": "ANOMALOUS"},
                {"timestamp": "T-120s", "parameter": "OBC_temp_C",
                 "value": 18.2, "status": "NOMINAL"},
                {"timestamp": "T-10s", "parameter": "OBC_temp_C",
                 "value": 18.2, "status": "NOMINAL"},
            ],
            "pre_fault_telemetry": [
                {"parameter": "I_sa", "value": 0.0},
                {"parameter": "V_bat", "value": 21.8},
                {"parameter": "V_bus", "value": 24.1},
                {"parameter": "Heater_power_W", "value": 15.0},
                {"parameter": "Attitude_error_deg", "value": 0.004},
                {"parameter": "OBC_temp_C", "value": 18.2},
            ],
            "event_log": [
                {"timestamp": "T-300s", "source": "EPS_SENSORS",
                 "message": "Solar Array A Current dropped to 0A (expected: 8.5A)"},
                {"timestamp": "T-180s", "source": "EPS_MANAGER",
                 "message": "State of Charge low (14.2%). Starting load shedding."},
                {"timestamp": "T-120s", "source": "OBC_CORE",
                 "message": "Command issued: Power off PYLD subsystem"},
                {"timestamp": "T-0s", "source": "FDIR_CORE",
                 "message": "Safe Mode entry triggered by EPS_UNDER_VOLT"},
            ],
            "hardware_state": {
                "solar_relay": "open",
                "battery_relays": "closed",
                "shed_status": "active",
            },
            "operating_context": {
                "eclipse_fraction": 0.0,
                "sun_sensor_angle_deg": 42.0,
                "time_since_contact_s": 2400,
            },
        },
        # ── Scenario 3: OBC Software Fault ────────────────────────────────
        {
            "scenario_id": 3,
            "fault_type": "OBC_WATCHDOG_OVERFLOW",
            "provenance": Provenance.SYNTHETIC.value,
            "source_note": "Simulated crash dump based on watchdog timer overflow behaviour. Not spacecraft data.",
            "incident_id": "INC-2026-0003",
            "fault_register": "0x00000040",
            "safe_mode_trigger": "WATCHDOG_RESET",
            "telecommand_context": {
                "event_id": 3,
                "telecommand": "telecommand_01",
                "execution_timestamp": "2026-06-12T04:25:55Z",
                "gap_seconds": 10.0,
                "gap_classification": "nominal",
                "gap_percentile": 50.0,
                "anomaly_flag": False,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-180s", "parameter": "CPU_load_pct",
                 "value": 100.0, "status": "CRITICAL"},
                {"timestamp": "T-180s", "parameter": "SoC_pct",
                 "value": 90.0, "status": "NOMINAL"},
                {"timestamp": "T-180s", "parameter": "V_bat",
                 "value": 31.1, "status": "NOMINAL"},
                {"timestamp": "T-180s", "parameter": "V_bus",
                 "value": 30.5, "status": "NOMINAL"},
                {"timestamp": "T-180s", "parameter": "I_sa",
                 "value": 8.3, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "Memory_usage_MB",
                 "value": 495.0, "status": "ANOMALOUS"},
                {"timestamp": "T-120s", "parameter": "Watchdog_counter",
                 "value": 995.0, "status": "NOMINAL"},
                {"timestamp": "T-10s", "parameter": "Watchdog_counter",
                 "value": 1002.0, "status": "CRITICAL"},
                {"timestamp": "T-10s", "parameter": "V_bat",
                 "value": 31.1, "status": "NOMINAL"},
                {"timestamp": "T-10s", "parameter": "SoC_pct",
                 "value": 89.8, "status": "NOMINAL"},
                {"timestamp": "T-10s", "parameter": "I_sa",
                 "value": 8.3, "status": "NOMINAL"},
            ],
            "pre_fault_telemetry": [
                {"parameter": "CPU_load_pct", "value": 100.0},
                {"parameter": "Memory_usage_MB", "value": 495.0},
                {"parameter": "Watchdog_counter", "value": 1002.0},
                {"parameter": "V_bat", "value": 31.1},
                {"parameter": "SoC_pct", "value": 90.0},
                {"parameter": "Attitude_error_deg", "value": 0.003},
            ],
            "event_log": [
                {"timestamp": "T-180s", "source": "OBC_MONITOR",
                 "message": "CPU load exceeded 95%"},
                {"timestamp": "T-120s", "source": "OBC_MONITOR",
                 "message": "Memory leak signature detected in thread 'attitude_control'"},
                {"timestamp": "T-10s", "source": "WATCHDOG_TIMER",
                 "message": "Watchdog counter exceeded limit (value=1002)"},
                {"timestamp": "T-0s", "source": "OBC_BOOT",
                 "message": "Watchdog reset triggered. Booting in Safe Mode."},
            ],
            "hardware_state": {
                "watchdog_state": "expired",
                "active_bank": "EEPROM_B",
                "last_reboot_cause": "WATCHDOG_RESET",
            },
            "operating_context": {
                "eclipse_fraction": 0.2,
                "sun_sensor_angle_deg": 15.0,
                "time_since_contact_s": 50,
            },
        },
        # ── Scenario 5: TCS Thermal Runaway ──────────────────────────────
        {
            "scenario_id": 5,
            "fault_type": "TCS_THERMAL_RUNAWAY",
            "provenance": Provenance.SYNTHETIC.value,
            "source_note": "Simulated thermal runaway scenario modelled on ECSS-Q-ST-30-02C thermal failure signatures. Not spacecraft data.",
            "incident_id": "INC-2026-0005",
            "fault_register": "0x00000100",
            "safe_mode_trigger": "TCS_OVERTEMP",
            "telecommand_context": {
                "event_id": 5,
                "telecommand": "telecommand_28",
                "execution_timestamp": "2026-06-12T14:22:03Z",
                "gap_seconds": None,
                "gap_classification": "not_provided",
                "gap_percentile": None,
                "anomaly_flag": True,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-600s", "parameter": "Heater_power_W",
                 "value": 0.0, "status": "NOMINAL"},
                {"timestamp": "T-600s", "parameter": "Component_temp_C",
                 "value": 25.0, "status": "NOMINAL"},
                {"timestamp": "T-300s", "parameter": "Panel_temp_C",
                 "value": 78.0, "status": "WARNING"},
                {"timestamp": "T-300s", "parameter": "Component_temp_C",
                 "value": 45.0, "status": "WARNING"},
                {"timestamp": "T-60s", "parameter": "OBC_temp_C",
                 "value": 62.5, "status": "CRITICAL"},
                {"timestamp": "T-60s", "parameter": "Component_temp_C",
                 "value": 50.0, "status": "CRITICAL"},
                {"timestamp": "T-60s", "parameter": "Heater_power_W",
                 "value": 22.0, "status": "NOMINAL"},
                {"timestamp": "T-0s", "parameter": "Battery_temp_C",
                 "value": 48.2, "status": "CRITICAL"},
                {"timestamp": "T-0s", "parameter": "Component_temp_C",
                 "value": 64.0, "status": "CRITICAL"},
                {"timestamp": "T-0s", "parameter": "Heater_power_W",
                 "value": 22.0, "status": "NOMINAL"},
            ],
            "pre_fault_telemetry": [
                {"parameter": "OBC_temp_C", "value": 62.5},
                {"parameter": "Panel_temp_C", "value": 78.0},
                {"parameter": "Battery_temp_C", "value": 48.2},
                {"parameter": "Heater_power_W", "value": 22.0},
                {"parameter": "Radiator_eff_pct", "value": 12.0},
                {"parameter": "V_bat", "value": 29.5},
                {"parameter": "SoC_pct", "value": 72.0},
            ],
            "event_log": [
                {"timestamp": "T-600s", "source": "TCS_MONITOR",
                 "message": "Radiator efficiency dropped below 20% (12.0%)"},
                {"timestamp": "T-300s", "source": "TCS_MANAGER",
                 "message": "Panel temperature rising: 78.0°C (limit: 70°C)"},
                {"timestamp": "T-60s", "source": "TCS_MANAGER",
                 "message": "OBC temperature critical: 62.5°C (limit: 60°C). Heaters disabled."},
                {"timestamp": "T-0s", "source": "FDIR_CORE",
                 "message": "Safe Mode entry triggered by TCS_OVERTEMP"},
            ],
            "hardware_state": {
                "heater_zones_active": 0,
                "radiator_state": "degraded",
                "louver_position": "fully_open",
            },
            "operating_context": {
                "eclipse_fraction": 0.0,
                "sun_sensor_angle_deg": 5.0,
                "time_since_contact_s": 800,
            },
        },
        # ── Scenario 6: COMMS Transponder Loss ───────────────────────────
        {
            "scenario_id": 6,
            "fault_type": "COMMS_TRANSPONDER_LOSS",
            "provenance": Provenance.SYNTHETIC.value,
            "source_note": "Simulated communication loss scenario. Transponder lockout with loss of downlink signal. Not spacecraft data.",
            "incident_id": "INC-2026-0006",
            "fault_register": "0x00000200",
            "safe_mode_trigger": "COMMS_LOSS",
            "telecommand_context": {
                "event_id": 6,
                "telecommand": "telecommand_31",
                "execution_timestamp": "2026-06-12T18:45:17Z",
                "gap_seconds": None,
                "gap_classification": "not_provided",
                "gap_percentile": None,
                "anomaly_flag": True,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-900s", "parameter": "RF_power_dBm",
                 "value": -85.0, "status": "NOMINAL"},
                {"timestamp": "T-900s", "parameter": "SoC_pct",
                 "value": 88.0, "status": "NOMINAL"},
                {"timestamp": "T-900s", "parameter": "V_bat",
                 "value": 30.8, "status": "NOMINAL"},
                {"timestamp": "T-900s", "parameter": "V_bus",
                 "value": 30.2, "status": "NOMINAL"},
                {"timestamp": "T-900s", "parameter": "I_sa",
                 "value": 8.2, "status": "NOMINAL"},
                {"timestamp": "T-900s", "parameter": "Heater_power_W",
                 "value": 12.0, "status": "NOMINAL"},
                {"timestamp": "T-600s", "parameter": "RF_power_dBm",
                 "value": -92.0, "status": "WARNING"},
                {"timestamp": "T-600s", "parameter": "SoC_pct",
                 "value": 87.9, "status": "NOMINAL"},
                {"timestamp": "T-600s", "parameter": "I_sa",
                 "value": 8.2, "status": "NOMINAL"},
                {"timestamp": "T-600s", "parameter": "V_bus",
                 "value": 30.1, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "Bit_error_rate",
                 "value": 0.08, "status": "CRITICAL"},
                {"timestamp": "T-120s", "parameter": "V_bat",
                 "value": 30.8, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "SoC_pct",
                 "value": 87.9, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "I_sa",
                 "value": 8.2, "status": "NOMINAL"},
                {"timestamp": "T-120s", "parameter": "V_bus",
                 "value": 30.1, "status": "NOMINAL"},
                {"timestamp": "T-0s", "parameter": "Link_status",
                 "value": 0, "status": "CRITICAL"},
            ],
            "pre_fault_telemetry": [
                {"parameter": "RF_power_dBm", "value": -102.0},
                {"parameter": "Bit_error_rate", "value": 0.08},
                {"parameter": "Transponder_temp_C", "value": 55.0},
                {"parameter": "Link_margin_dB", "value": -3.5},
                {"parameter": "Antenna_pointing_error_deg", "value": 4.2},
                {"parameter": "V_bat", "value": 30.8},
                {"parameter": "SoC_pct", "value": 88.0},
            ],
            "event_log": [
                {"timestamp": "T-900s", "source": "COMMS_MONITOR",
                 "message": "RF signal strength degrading: -92 dBm (threshold: -95 dBm)"},
                {"timestamp": "T-600s", "source": "COMMS_MANAGER",
                 "message": "Bit error rate elevated: 0.08 (nominal: <0.001)"},
                {"timestamp": "T-120s", "source": "COMMS_TRANSPONDER",
                 "message": "Transponder lock lost. Switching to backup receiver."},
                {"timestamp": "T-0s", "source": "FDIR_CORE",
                 "message": "Safe Mode entry triggered by COMMS_LOSS. Autonomous beacon mode activated."},
            ],
            "hardware_state": {
                "transponder_state": "no_lock",
                "antenna_mode": "omni_fallback",
                "backup_receiver": "active",
            },
            "operating_context": {
                "eclipse_fraction": 0.35,
                "sun_sensor_angle_deg": 28.0,
                "time_since_contact_s": 7200,
            },
        },
        # ── Scenario 4: Real ESA-ADB Anomaly (id_109) ─────────────────────
        {
            "scenario_id": 4,
            "fault_type": "ESA_ADB_ANOMALY",
            # REAL: these numeric values were read from the ESA-ADB channel
            # pickles by data_tools/esa_adb_crash_dump.py.
            "provenance": Provenance.REAL.value,
            "source_note": (
                "Numeric telemetry read directly from the ESA Anomaly Detection Benchmark "
                "(Mission 1, id_109). Channel names are anonymized; no root-cause label or "
                "recovery command is available. "
                "Do NOT claim this as a confirmed safe-mode crash or a confirmed subsystem root cause."
            ),
            "incident_id": "ESA-Mission1-id_109",
            "fault_register": "ESA_LABEL:id_109;CLASS:class_3;SUBCLASS:subclass_2",
            "safe_mode_trigger": "ESA_ADB_LABEL",
            "telecommand_context": {
                "event_id": 109,
                "telecommand": "telecommand_12",
                "execution_timestamp": "2006-09-25T19:55:49Z",
                "gap_seconds": None,
                "gap_classification": "not_provided",
                "gap_percentile": None,
                "anomaly_flag": True,
            },
            "pre_fault_telemetry_window": [
                {"timestamp": "T-593s", "parameter": "channel_41",
                 "value": 0.816503, "status": "NOMINAL"},
                {"timestamp": "T-593s", "parameter": "channel_42",
                 "value": 0.772688, "status": "NOMINAL"},
                {"timestamp": "T+0s", "parameter": "channel_41",
                 "value": 0.960135, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+0s", "parameter": "channel_42",
                 "value": 0.0, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+0s", "parameter": "channel_43",
                 "value": 0.93332, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+0s", "parameter": "channel_44",
                 "value": 0.947167, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+0s", "parameter": "channel_45",
                 "value": 0.977107, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+0s", "parameter": "channel_46",
                 "value": 0.95193, "status": "LABELLED_ANOMALY"},
                {"timestamp": "T+67s", "parameter": "channel_41",
                 "value": 0.80316, "status": "NOMINAL"},
            ],
            "pre_fault_telemetry": [
                {"parameter": "channel_41", "value": 0.960135,
                 "nominal_min": 0.797548, "nominal_max": 0.82607},
                {"parameter": "channel_42", "value": 0.0,
                 "nominal_min": 0.764285, "nominal_max": 0.806006},
                {"parameter": "channel_43", "value": 0.93332,
                 "nominal_min": 0.758193, "nominal_max": 0.786285},
                {"parameter": "channel_44", "value": 0.947167,
                 "nominal_min": 0.780812, "nominal_max": 0.815033},
                {"parameter": "channel_45", "value": 0.977107,
                 "nominal_min": 0.797574, "nominal_max": 0.829473},
                {"parameter": "channel_46", "value": 0.95193,
                 "nominal_min": 0.747717, "nominal_max": 0.78975},
            ],
            "event_log": [
                {"timestamp": "T+0s", "source": "ESA_ADB_LABEL",
                 "message": "id_109 labelled Anomaly starts; class=class_3"},
                {"timestamp": "T+7s", "source": "ESA_ADB_LABEL",
                 "message": "id_109 labelled interval ends"},
            ],
            "hardware_state": {
                "last_reset_cause": "NOT_PROVIDED_BY_ESA_ADB",
                "watchdog_status": "NOT_PROVIDED_BY_ESA_ADB",
            },
            "operating_context": {
                "source_dataset": "ESA Anomaly Dataset / ESA-ADB",
                "mission_folder": "ESA-Mission1",
                "label_id": "id_109",
                "eclipse_fraction": None,
                "sun_sensor_angle_deg": None,
                "time_since_contact_s": None,
            },
        },
    ]


def _load_esa_scenarios_from_disk() -> list[dict[str, Any]]:
    """Dynamically load ESA crash dump JSONs from data/esa_crash_dumps/.

    Returns additional scenario dicts built from compact sentinel-only
    crash dump files. These supplement the hardcoded id_109 above.
    Errors are logged but never crash the server.

    Provenance is read from each file's own ``provenance`` field and is never
    assumed. A file that does not declare its provenance is surfaced as
    UNKNOWN, not as REAL. This function previously stamped every file it
    loaded as "Real ESA Telemetry", which mislabelled files whose numeric
    values were synthesized from real metadata.
    """
    esa_dir = os.path.join(
        os.path.dirname(__file__), "..", "..", "data", "esa_crash_dumps"
    )
    if not os.path.isdir(esa_dir):
        return []

    extra: list[dict[str, Any]] = []
    for fname in sorted(os.listdir(esa_dir)):
        if not fname.endswith("_sentinel_only.json"):
            continue
        # Skip id_109 — already hardcoded above
        if "id_109" in fname:
            continue
        try:
            with open(os.path.join(esa_dir, fname), "r", encoding="utf-8") as fh:
                dump = json.load(fh)

            # Derive the display fields from the file's declared provenance.
            # describe() normalizes unknown/missing values away from REAL.
            resolved = describe(dump)
            dump.update(resolved)

            if resolved["provenance"] == Provenance.UNKNOWN.value:
                logger.warning(
                    "ESA scenario %s declares no provenance — surfacing as UNKNOWN",
                    fname,
                )

            extra.append(dump)
        except Exception as exc:
            logger.warning("Failed to load ESA scenario %s: %s", fname, exc)

    return extra


def get_all_scenarios() -> list[dict[str, Any]]:
    """Return preset + dynamically loaded ESA scenarios.

    This is the preferred public API. Falls back to just presets
    if ESA loading fails.

    Every returned scenario is guaranteed to carry a ``provenance`` code and a
    ``source_type`` label derived from it, so the frontend never has to guess
    and can never be handed a "real" label for generated numbers.
    """
    presets = get_preset_scenarios()
    for scenario in presets:
        scenario.update(describe(scenario))
        # Phase 5: bounds come from the channel dictionary, not from literals
        # repeated in this file.
        _fill_bounds_from_dictionary(scenario)

    try:
        esa_extra = _load_esa_scenarios_from_disk()
    except Exception as exc:
        logger.warning("ESA dynamic loader failed: %s", exc)
        return presets

    return presets + esa_extra

