"""
SENTINEL — Data Provenance Vocabulary (provenance.py)

Phase 0 ("Truth in Labeling"). This module is the single source of truth for
how SENTINEL describes where a telemetry payload came from.

The rule this module exists to enforce:

    A scenario may only be labelled REAL when the *numeric telemetry values
    themselves* were read from the source dataset. Real identifiers, real
    timestamps, real channel names, or real anomaly-class metadata are NOT
    sufficient — if the numbers were generated, the provenance is
    SYNTHETIC_FROM_REAL_METADATA.

Machine-readable code goes in the ``provenance`` field. The human-readable
string in ``source_type`` is derived from it so the two can never drift.

Usage:
    from app.api.provenance import Provenance, display_label, describe

    scenario["provenance"] = Provenance.SYNTHETIC
    scenario["source_type"] = display_label(Provenance.SYNTHETIC)
"""

from __future__ import annotations

from enum import Enum
from typing import Any


class Provenance(str, Enum):
    """Where the numeric telemetry in a payload actually came from."""

    REAL = "REAL"
    """Numeric telemetry values were read from a real mission dataset."""

    SYNTHETIC = "SYNTHETIC"
    """Numeric telemetry values were generated by SENTINEL's simulator."""

    SYNTHETIC_FROM_REAL_METADATA = "SYNTHETIC_FROM_REAL_METADATA"
    """Real identifiers/labels/timestamps, but generated numeric values."""

    DEMO = "DEMO"
    """A scripted replay staged for demonstration.

    Phase 4 added this. It is deliberately distinct from SYNTHETIC: synthetic
    telemetry is generated but still analysed for real, whereas a DEMO payload is
    part of a rehearsed walkthrough whose outcome is known in advance. An audit
    record must be able to say which one it was, otherwise a demo run and a real
    analysis of simulated data are indistinguishable after the fact.
    """

    UNKNOWN = "UNKNOWN"
    """Provenance could not be determined. Treat as not-real."""


# Human-readable label shown in the UI. Deliberately uppercase and blunt.
_DISPLAY_LABELS: dict[str, str] = {
    Provenance.REAL.value: "REAL ESA TELEMETRY",
    Provenance.SYNTHETIC.value: "SYNTHETIC DATA",
    Provenance.SYNTHETIC_FROM_REAL_METADATA.value: "SYNTHETIC FROM REAL METADATA",
    Provenance.DEMO.value: "DEMO / REPLAY",
    Provenance.UNKNOWN.value: "PROVENANCE UNKNOWN",
}

# One-sentence disclaimer appended when a scenario has no note of its own.
_DEFAULT_NOTES: dict[str, str] = {
    Provenance.REAL.value: (
        "Numeric telemetry values are read directly from the source mission "
        "dataset. Channel names are anonymized and no root-cause label or "
        "recovery command is available."
    ),
    Provenance.SYNTHETIC.value: (
        "Simulated telemetry generated by SENTINEL. Not spacecraft data. "
        "Not a record of a real safe-mode event."
    ),
    Provenance.SYNTHETIC_FROM_REAL_METADATA.value: (
        "Identifiers, timestamps, channel names and anomaly-class metadata are "
        "real; the numeric telemetry values are SYNTHESIZED by SENTINEL and are "
        "not measurements. Do not cite these values as real telemetry."
    ),
    Provenance.DEMO.value: (
        "Scripted demonstration replay. The payload and the narration are "
        "rehearsed; this is not a live investigation and the outcome was known "
        "before the run started."
    ),
    Provenance.UNKNOWN.value: (
        "Provenance of this payload could not be determined. Do not treat it "
        "as real telemetry."
    ),
}


def display_label(provenance: str | Provenance) -> str:
    """Return the UI-facing label for a provenance code."""
    key = provenance.value if isinstance(provenance, Provenance) else str(provenance)
    return _DISPLAY_LABELS.get(key, _DISPLAY_LABELS[Provenance.UNKNOWN.value])


def default_note(provenance: str | Provenance) -> str:
    """Return the default disclaimer sentence for a provenance code."""
    key = provenance.value if isinstance(provenance, Provenance) else str(provenance)
    return _DEFAULT_NOTES.get(key, _DEFAULT_NOTES[Provenance.UNKNOWN.value])


def is_real(provenance: str | Provenance | None) -> bool:
    """True only for REAL. Everything else — including UNKNOWN — is not real."""
    if provenance is None:
        return False
    key = provenance.value if isinstance(provenance, Provenance) else str(provenance)
    return key == Provenance.REAL.value


def normalize(value: Any) -> str:
    """Coerce an arbitrary provenance value to a known code.

    Unrecognised values become UNKNOWN rather than silently passing through,
    so a typo can never be rendered as REAL.

    CASE IS SIGNIFICANT. ``"real"`` resolves to UNKNOWN, not REAL.

    This was case-insensitive until Phase 4, when the audit work surfaced the
    divergence: the frontend's ``normalizeProvenance()`` has always been an exact
    lookup, so a payload declaring ``"real"`` was shown as PROVENANCE UNKNOWN in
    the browser while the backend promoted it to REAL — the two sides disagreeing
    about the single field that carries the strongest claim in the system.

    Exact matching is the safer side of that disagreement and the correct one:
    ``provenance`` is a machine-readable code, every writer in the repository
    emits ``Provenance.X.value``, and a value in different casing is therefore
    not something this system produced. Answering UNKNOWN for it is honest, and
    it fails towards "not real". Surrounding whitespace is still tolerated,
    because that is a transport artifact rather than a different value.
    """
    if value is None:
        return Provenance.UNKNOWN.value
    key = value.value if isinstance(value, Provenance) else str(value).strip()
    if key in _DISPLAY_LABELS:
        return key
    return Provenance.UNKNOWN.value


def describe(payload: dict[str, Any]) -> dict[str, str]:
    """Return the provenance triplet for a scenario dict.

    Reads the payload's declared ``provenance`` and returns the normalized
    code plus its derived display label and note. Never trusts an existing
    ``source_type`` string, because that is exactly the field that drifted.
    """
    code = normalize(payload.get("provenance"))
    return {
        "provenance": code,
        "source_type": display_label(code),
        "source_note": payload.get("source_note") or default_note(code),
    }


def stamp(payload: dict[str, Any], provenance: str | Provenance) -> dict[str, Any]:
    """Set provenance on a payload in place and derive its display fields.

    Preserves an existing ``source_note`` if the payload already has one,
    otherwise fills in the default disclaimer.
    """
    code = normalize(provenance)
    payload["provenance"] = code
    payload["source_type"] = display_label(code)
    if not payload.get("source_note"):
        payload["source_note"] = default_note(code)
    return payload
